In [1]:
import os
import time
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import math
from sklearn.model_selection import train_test_split
from sklearn import metrics

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation, CuDNNGRU, Conv1D
from keras.layers import Bidirectional, GlobalMaxPool1D
from keras.models import Model
from keras import initializers, regularizers, constraints, optimizers, layers
from sklearn.feature_extraction.text import TfidfVectorizer


Using TensorFlow backend.


In [2]:
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
print("Train shape : ",train_df.shape)
print("Test shape : ",test_df.shape)


Train shape :  (1306122, 3)
Test shape :  (375806, 2)


In [3]:
print(train_df.columns)


Index(['qid', 'question_text', 'target'], dtype='object')


In [5]:
maxlen = 72

vectorizer = TfidfVectorizer(
    strip_accents='unicode',
    ngram_range=(1, 3),
    analyzer='word',
    min_df=3, max_df=0.9, max_features=None,
    use_idf=True, smooth_idf=True, sublinear_tf=True,
    stop_words='english')

train_df["question_text"] = train_df["question_text"].str.lower()
test_df["question_text"] = test_df["question_text"].str.lower()

X = train_df["question_text"].fillna("_NA").values
X_test = test_df["question_text"].fillna("_NA").values

print(X)

tokenizer = Tokenizer()
tokenizer.fit_on_texts(list(X))

X = tokenizer.texts_to_sequences(X)
X_test = tokenizer.texts_to_sequences(X_test)

print(X)

X = pad_sequences(X, maxlen=maxlen)
X_test = pad_sequences(X_test, maxlen=maxlen)

print(X)

['how did quebec nationalists see their province as a nation in the 1960s?'
 'do you have an adopted dog, how would you encourage people to adopt and not shop?'
 'why does velocity affect time? does velocity affect space geometry?' ...
 'is foam insulation toxic?'
 'how can one start a research project based on biochemistry at ug level?'
 'who wins in a battle between a wolverine and a puma?']
[[    0     0     0 ...     6     1  8333]
 [    0     0     0 ...    10    44  1846]
 [    0     0     0 ...   374   451  5546]
 ...
 [    0     0     0 ...  7760 11663  2984]
 [    0     0     0 ...    43  3384   422]
 [    0     0     0 ...    10     4 21972]]


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

